global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: megasegashop
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - api-gateway:8080
          - auth-service:8081
          - user-service:8082
          - product-service:8083
          - cart-service:8084
          - inventory-service:8085
          - order-service:8086
          - notification-service:8087
          - payment-service:8088
          - discovery-server:8761
          - config-server:8888
